# reload config
bind=SUPER+SHIFT,r,reload_config

# menu and terminal
bind=SUPER,r,spawn,fuzzel
bind=SUPER,Return,spawn,foot

# exit
bind=SUPER+SHIFT,x,quit
bind=SUPER,c,killclient,

# switch window focus
bind=SUPER,j,focusstack,next
bind=SUPER,k,focusstack,previous

# swap window
bind=SUPER,z,exchange_client,left

# switch window status
bind=SUPER,g,toggleglobal,
bind=SUPER,backslash,togglefloating,
bind=SUPER,m,togglemaximizescreen,
bind=SUPER,f,togglefullscreen,
bind=SUPER,i,minimized,
bind=SUPER,o,toggleoverlay,
bind=SUPER+SHIFT,I,restore_minimized
bind=SUPER,z,toggle_scratchpad

# switch layouts
bind=SUPER,t,setlayout,tile
bind=SUPER,f,setlayout,floating

# scroller layout
bind=SUPER,e,set_proportion,+0.1
bind=SUPER,x,switch_proportion_preset,

# switch layout
bind=SUPER,n,switch_layout

# tag switch
bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0
bind=SUPER,0,toggleoverview,

# tag: move client to the tag and focus it
# tagsilent: move client to the tag and not focus it
# bind=Alt,1,tagsilent,1
bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
bind=SUPER+SHIFT,6,tag,6,0
bind=SUPER+SHIFT,7,tag,7,0
bind=SUPER+SHIFT,8,tag,8,0
bind=SUPER+SHIFT,9,tag,9,0

# monitor switch
bind=SUPER,period,focusmon,right
bind=SUPER+SHIFT,period,tagmon,right

# function keys
bind=NONE,XF86AudioRaiseVolume,spawn,amixer -q set Master 5%+ unmute
bind=NONE,XF86AudioLowerVolume,spawn,amixer -q set Master 5%- unmute
bind=NONE,XF86AudioMute,spawn,amixer -q set Master toggle
bind=NONE,XF86MonBrightnessUp,spawn,light -A 10
bind=NONE,XF86MonBrightnessDown,spawn,light -U 10

# screenshots
bind=SUPER,s,spawn,${HOME}/.config/mango/scripts/screencapture
bind=SUPER+SHIFT,S,spawn,${HOME}/.config/mango/scripts/capture

bind=SUPER+SHIFT,w,spawn,wallpapermenu

bind=SUPER+SHIFT,L,spawn,hyprlock

# movewin
bind=CTRL+SHIFT,Up,movewin,+0,-50
bind=CTRL+SHIFT,Down,movewin,+0,+50
bind=CTRL+SHIFT,Left,movewin,-50,+0
bind=CTRL+SHIFT,Right,movewin,+50,+0

# resizewin
bind=SUPER,h,resizewin,-50,+0
bind=SUPER,l,resizewin,+50,+0

# mouse
# btn_left and btn_right can't bind none mod key
mouse_natural_scrolling=0
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=NONE,btn_middle,togglemaximizescreen,0
mousebind=SUPER,btn_right,moveresize,curresize


# Axis Bindings
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client
