env=QT_AUTO_SCREEN_SCALE_FACTOR,1
env=QT_WAYLAND_FORCE_DPI,100

exec=~/.config/mango/scripts/scale

monitorrule=name:eDP-1,width:1920,height:1080,x:0,y:0,scale:1.3
monitorrule=name:HDMI-A-1,width:1920,height:1200,x:1476,y:0,scale:1
monitorrule=name:^DP-1,width:1920,height:1200,x:1476,y:0,scale:1
